### ISSUE TITLE
Fails to compile with QE 6.2

### ISSUE THREAD

**Issue by stur86** [dceresoli/qe-gipaw#1]
I have tried compiling the latest version with Quantum Espresso 6.2 but fail. The error seems to be in the interface of `fft_type_descriptor` (see attached log: [error.log](https://github.com/dceresoli/qe-gipaw/files/1736583/error.log) ). I can't use this new version in any other way, as `make gipaw` in QE 6.2 gives an error as their GIPAW version is still 6.1, and that version has a bug which causes symmetrized hyperfine tensors to become zero (from the commit messages, I imagine this was fixed in 6.2). Thanks!

**Comment by dceresoli** [comment]
I'm working on that. The git HEAD version compiles correctly with qe-6.2.1. I have to do extensive testing.

**Comment by stur86** [comment]
Ok, thanks! Would you say that means I'm better off sticking with 6.1 right now, or is 6.2 tested enough I can trust it for basic tasks?

**Comment by dceresoli** [comment]
Yes, please, stick with 6.1. Moreover FFT in 6.2 is slower for small systems. Once I can reproduce tests with 6.2, I'll create a new release.

**Comment by stur86** [comment]
Ok, thanks!
