### ISSUE TITLE
More calculation metadata in the .magres file

### ISSUE THREAD

**Issue by jkshenton** [dceresoli/qe-gipaw#17]
Hi! 

Would it be possible to include more calculation metadata in the [calculation] block of the .magres files? 

i.e. here:

https://github.com/dceresoli/qe-gipaw/blob/100c4c5b9f438fe73324a0c7548eba1e54907b7a/src/output_magres.f90#L127

This would be very useful for future entries in e.g. the [CCP-NC database](https://www.ccpnc.ac.uk/database/), making them more FAIR. As an example, CASTEP outputs the following sort of information:

```
calc_code CASTEP
calc_code_version  16.1
calc_code_hgversion f8ea1bd8badc+  Tue, 08 Dec 2015 11:54:45 +0000                  
calc_code_platform linux_x86_64_ifort15                                            
calc_name ethanol_crystal
calc_comment                                                                                 
calc_xcfunctional PBE 
calc_cutoffenergy    800.00000000 eV
calc_pspot H 1|0.6|13|15|17|10(qc=8)
calc_pspot C 2|1.4|10|12|13|20:21(qc=7)
calc_pspot O 2|1.1|15|18|20|20:21(qc=7)
calc_kpoint_mp_grid 3 2 2
calc_kpoint_mp_offset       0.00000000      0.00000000      0.00000000
```

Adding in as much relevant information as possible would be helpful, ideally following a similar naming convention to CASTEP, where possible.

Many thanks!

**Comment by dceresoli** [comment]
Done!
D.
