### ISSUE TITLE
Fails to compile with QE 7.3.1

### ISSUE THREAD

**Issue by Crivella** [dceresoli/qe-gipaw#19]
It seems that due to the [renaming](https://gitlab.com/QEF/q-e/-/commit/e44da33695f4786c396576cb3aab3e42bfafe0bd) of the `tab` variable to `tab_beta`  in `uspp_data` and successive [deletion](https://gitlab.com/QEF/q-e/-/commit/d6146e551775ebd93d53f28b3d848a4ba0fc5b45) the compilation of gipaw in qe 7.3.1 fails with the following error

```
~/Codes/QE/7.3.1-cmake/external/qe-gipaw/src/gipaw_setup.f90:524:36:

  524 |   USE uspp_data,     ONLY : nqx, dq, tab
      |                                    1
Error: Symbol ‘tab’ referenced at (1) not found in module ‘uspp_data’
~/Codes/QE/7.3.1-cmake/external/qe-gipaw/src/gipaw_setup.f90:546:21:

  546 |            d1 = (tab(2,nb,nt) - tab(1,nb,nt)) / dq
      |                     1
Error: Expected a right parenthesis in expression at (1)
~/Codes/QE/7.3.1-cmake/external/qe-gipaw/src/gipaw_setup.f90:547:34:

  547 |            call spline(xdata, tab(:,nb,nt), 0.d0, d1, tab_d2y(:,nb,nt))
      |                                  1
Error: Syntax error in argument list at (1)
~/Codes/QE/7.3.1-cmake/external/qe-gipaw/src/gipaw_setup.f90:536:28:

  536 |   allocate(tab_d2y, mold=tab)
      |                            1
Error: Symbol ‘tab’ at (1) has no IMPLICIT type
```

**Comment by dceresoli** [comment]
thank you for pointing out, I'm working on it

**Comment by dceresoli** [comment]
Fixed!

**Comment by PelikanAA** [comment]
Hi,

I'm having a big issue with this; with QE 7.2 Regarding the spline_ps being removed from the scf input; removal of spline_ps will allow the pw.x scf convergence to occur, but then attempting to run gipaw.x fails with/or without spline_ps in the nmr.in tests.

**Comment by dceresoli** [comment]
Hi. I don't understand your issues.
Are those issues related to qe-7.2? or to qe-7.3.1? 
can you send me your input/output files? and describe what are you doing in detail.
D.
