### ISSUE TITLE
Source compatible to QE6.4

### ISSUE THREAD

**Issue by dumindasamarakoon** [dceresoli/qe-gipaw#6]
Dear Sir,

Quantum espresso install/plugins_list have listed the qe-gipaw version as follows,

# Package maintainer: Davide Ceresoli
GIPAW=qe-gipaw-6.4
GIPAW_URL=https://github.com/dceresoli/qe-gipaw/archive/6.4.tar.gz
#

I'm having some issues with the compilation of gipaw with make command.

Is this the write version ?

**Comment by dceresoli** [comment]
the changes in qe-6.4 have broken many of the gipaw features. I'm doing the porting, it will take same time.

**Comment by dumindasamarakoon** [comment]
Dear Sir,
Thank you very much for the clarification and for your efforts.
