### ISSUE TITLE
Spin–orbit effects in GIPAW?

### ISSUE THREAD

**Issue by chrinide** [dceresoli/qe-gipaw#7]
Dear GIPAW developers,

It is possible to include Spin–orbit effects in GIPAW?  How could I do a Spin–orbit included GIPAW caculation? Or will be Spin–orbit effects available in GIPAW ?

**Comment by dceresoli** [comment]
We have plans to account for spin orbit using the ZORA formalism (JCP 118, 5748)
Best,
D.
